# Generated by Django 5.0.4 on 2024-05-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('privacidad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.TextField()),
                ('puesto', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_original', models.CharField(max_length=255)),
                ('popularidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('personaje', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoTecnico',
            fields=[
                ('id_equipotecnico', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.TextField()),
                ('puesto', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_original', models.CharField(max_length=255)),
                ('popularidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'equipo_tecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id_follow', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'follow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('privacidad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fechaestreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'pelicula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaLista',
            fields=[
                ('id_peliculalista', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pelicula_lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=255, unique=True)),
                ('rol', models.TextField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fotoperfil', models.CharField(blank=True, max_length=255, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('fechaultimavisita', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioLista',
            fields=[
                ('id_usuariolista', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaActor',
            fields=[
                ('id_pelicula', models.OneToOneField(db_column='id_pelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.pelicula')),
            ],
            options={
                'db_table': 'pelicula_actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaEquipotecnico',
            fields=[
                ('id_pelicula', models.OneToOneField(db_column='id_pelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.pelicula')),
            ],
            options={
                'db_table': 'pelicula_equipotecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id_pelicula', models.OneToOneField(db_column='id_pelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.pelicula')),
            ],
            options={
                'db_table': 'pelicula_genero',
                'managed': False,
            },
        ),
    ]
